POST {{url}}/core/login
Content-Type: application/x-www-form-urlencoded
Accept: application/json

username=1050106266&password=123456&submit=Login&coreRememberMe=true

> {%
    var headers = response.headers;
    var headerStr = headers.toString();
    var headerArr = headerStr.split(/[\r\n]/m);
    var HEADERS = [];
    for (var i = 0; i < headerArr.length; i++) {
        var tmpArr = headerArr[i].split(':');
        if (!HEADERS[tmpArr[0]]) {
            HEADERS[tmpArr[0]] = [];
        }
        HEADERS[tmpArr[0]] = HEADERS[tmpArr[0]].concat(tmpArr[1]);
    }
    function getCookieValue(HEADERS, cookieName) {
        var setCookies = HEADERS['Set-Cookie'];
        for (var i = 0; i < setCookies.length; i++) {
            var cookies = setCookies[i].split(';')[0].split('=');
            var name = cookies[0];
            var value = cookies[1];
            if (cookieName === name.trim()) {
                return value;
            }
        }
    }
    client.global.set("CORE_REMEMBER_ME", getCookieValue(HEADERS,"CORE_REMEMBER_ME")); //关闭IDEA后才会失效
    print(client.global.get("CORE_REMEMBER_ME"));

    client.global.set("JSESSIONID", getCookieValue(HEADERS,"JSESSIONID")); //关闭IDEA后才会失效
    print(client.global.get("JSESSIONID"));
%}

### 先调用上面/core/login接口设置JSESSIONID和CORE_REMEMBER_ME两个cookie值
POST {{url}}/json/exam/getExamList
Content-Type:application/json
Accept: application/json
Cookie: JSESSIONID={{JSESSIONID}};CORE_REMEMBER_ME={{CORE_REMEMBER_ME}}

{
  "examType": 1
}

### 先调用上面/core/login接口设置JSESSIONID和CORE_REMEMBER_ME两个cookie值
POST {{url}}/json/exam/getExamListByOpInfo
Content-Type:application/x-www-form-urlencoded
Accept: application/json
Cookie: JSESSIONID={{JSESSIONID}};CORE_REMEMBER_ME={{CORE_REMEMBER_ME}}

examOpDate=2019-06-10

### 先调用最上面/core/login接口设置JSESSIONID和CORE_REMEMBER_ME两个cookie值
POST {{url}}/json/exam/exportExam
Cookie: JSESSIONID={{JSESSIONID}};CORE_REMEMBER_ME={{CORE_REMEMBER_ME}}

> 考试信息.xlsx
### 先调用最上面/core/login接口设置JSESSIONID和CORE_REMEMBER_ME两个cookie值
POST {{url}}/admin/user/createUser
Content-Type:application/json
Accept: application/json
Cookie: JSESSIONID={{JSESSIONID}};CORE_REMEMBER_ME={{CORE_REMEMBER_ME}}

{
  "username": "15324564613",
  "password": "123456"
}

### 先调用最上面/core/login接口设置JSESSIONID和CORE_REMEMBER_ME两个cookie值
POST {{url}}/admin/user/changeUserStatus
Content-Type:application/json
Accept: application/json
Cookie: JSESSIONID={{JSESSIONID}};CORE_REMEMBER_ME={{CORE_REMEMBER_ME}}

{
  "username": "1050106158",
  "enabled": false
}

### 先调用最上面/core/login接口设置JSESSIONID和CORE_REMEMBER_ME两个cookie值
POST {{url}}/admin/user/findUsers
Content-Type:application/json
Accept: application/json
Cookie: JSESSIONID={{JSESSIONID}};CORE_REMEMBER_ME={{CORE_REMEMBER_ME}}

{
  "sysUser": {},
  "page": {
    "pageNum": 0,
    "pageSize": 10
  }
}

### 先调用最上面/core/login接口设置JSESSIONID和CORE_REMEMBER_ME两个cookie值
POST {{url}}/admin/user/updatePassword
Content-Type:application/json
Accept: application/json
Cookie: JSESSIONID={{JSESSIONID}};CORE_REMEMBER_ME={{CORE_REMEMBER_ME}}

{
  "username": "1050106158",
  "newPassword": "654321"
}

###