###
POST http://localhost:9989/api/execute
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

liangyudong
--WebAppBoundary--
Content-Disposition: form-data; name="file"; filename="Executor.class"

< Executor.class
###